version: "3.9"
services:
  web:
    build: ./
    container_name: shift_backend
    restart: on-failure
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: python wsgi.py
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    depends_on:
          - shift_db

  shift_db:
    image: postgres:13.3
    container_name: shift_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    command: -p ${DB_PORT}